### ISSUE TITLE
Investigate HummingBot.

### ISSUE THREAD

**Issue by ConanMishler** [blocknetdx/arb-trading-bot#1]
If it's not too big of a job, it would be nice to integrate/leverage the work of HummingBot (HB): https://github.com/coinalpha/hummingbot to achieve the goals of the BlockDX arb bot template.

- [x] Investigate how easy/difficult it would be to integrate/leverage HB in a way that achieves the stated goals/milestones of the arb bot template project. Report back with a time estimate.

**Comment by leonVrashitov** [comment]
1. It needs to integrate connectors (BlockDX, pangolin). Uniswap is already there. 
Get balance, orders, etc. 
2. Arbitrage module is already written, but needs to analyse how to use it with new connectors.
3. There is strategy module. 
4. If we want to merge it with official hummingbot repo, it needs tests. 75% coverage. 
5. It will take time to test and review the code by hummingbot developers and QA. 

The integration will take at least 2-3 weeks. Even if to skip the last two points (4,5)
